[package]
name = "gawsh"
version = "0.1.0"
edition = "2018"
license = "CC0-1.0"
authors = ["klardotsh <josh@klar.sh>"]

[dependencies]
anyhow = "1.0"
argh = "0.1.5"
console = "0.14"
# over = "0.6"
git2 = { version = "0.13", default_features = false }
indexmap = "1.7"
indicatif = { version = "0.16", features = ["improved_unicode"] }
lazy_static = "1.4"
maud = "0.22"
num_cpus = "1.13"
syntect = { version = "4.6", default-features = false, features = ["default-fancy"] }
threadpool = "1.8"
